load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_binary(
    name = "service1",
    embed = [":service1_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "service1_lib",
    srcs = ["service1.go"],
    importpath = "github.com/nikhildev/basil/services/service1",
    visibility = ["//visibility:private"],
    deps = ["//libraries/humanize_filesize"],
)

go_test(
    name = "service1_test",
    srcs = ["service1_test.go"],
    embed = [":service1_lib"],
)
